// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p1.proto

package com.autogeneratedby.polymorph;

public final class P1 {
  private P1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface allfieldsonceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autogeneratedby.polymorph.allfieldsonce)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * type before: bool 
     * </pre>
     *
     * <code>string some_boolean = 16;</code>
     * @return The someBoolean.
     */
    java.lang.String getSomeBoolean();
    /**
     * <pre>
     * type before: bool 
     * </pre>
     *
     * <code>string some_boolean = 16;</code>
     * @return The bytes for someBoolean.
     */
    com.google.protobuf.ByteString
        getSomeBooleanBytes();

    /**
     * <pre>
     * type before: fixed32 
     * </pre>
     *
     * <code>string some_fixed32 = 7;</code>
     * @return The someFixed32.
     */
    java.lang.String getSomeFixed32();
    /**
     * <pre>
     * type before: fixed32 
     * </pre>
     *
     * <code>string some_fixed32 = 7;</code>
     * @return The bytes for someFixed32.
     */
    com.google.protobuf.ByteString
        getSomeFixed32Bytes();

    /**
     * <pre>
     * type before: uint64 
     * </pre>
     *
     * <code>string some_uint64 = 19;</code>
     * @return The someUint64.
     */
    java.lang.String getSomeUint64();
    /**
     * <pre>
     * type before: uint64 
     * </pre>
     *
     * <code>string some_uint64 = 19;</code>
     * @return The bytes for someUint64.
     */
    com.google.protobuf.ByteString
        getSomeUint64Bytes();

    /**
     * <pre>
     * type before: sint64 | representation: negative number 
     * </pre>
     *
     * <code>sint64 some_sint64 = 12;</code>
     * @return The someSint64.
     */
    long getSomeSint64();

    /**
     * <pre>
     * type before: int64 | representation: negative number 
     * </pre>
     *
     * <code>int64 some_int64 = 14;</code>
     * @return The someInt64.
     */
    long getSomeInt64();

    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>double some_double = 8;</code>
     * @return The someDouble.
     */
    double getSomeDouble();

    /**
     * <pre>
     * type before: int32 | p2 
     * </pre>
     *
     * <code>int32 some_int32p2 = 18;</code>
     * @return The someInt32p2.
     */
    int getSomeInt32P2();

    /**
     * <pre>
     * type before: string | representation: utf32 bytes 
     * </pre>
     *
     * <code>bytes some_string = 10;</code>
     * @return The someString.
     */
    com.google.protobuf.ByteString getSomeString();

    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>sfixed32 some_sfixed32 = 6;</code>
     * @return The someSfixed32.
     */
    int getSomeSfixed32();

    /**
     * <pre>
     * type before: int32 | p1 
     * </pre>
     *
     * <code>int32 some_int32p1 = 17;</code>
     * @return The someInt32p1.
     */
    int getSomeInt32P1();

    /**
     * <pre>
     * type before: sint32 | representation: negative number 
     * </pre>
     *
     * <code>sint32 some_sint32 = 2;</code>
     * @return The someSint32.
     */
    int getSomeSint32();

    /**
     * <pre>
     * type before: bytes | representation: split bytes 
     * </pre>
     *
     * <code>bytes some_bytesp2 = 5;</code>
     * @return The someBytesp2.
     */
    com.google.protobuf.ByteString getSomeBytesp2();

    /**
     * <pre>
     * type before: float | representation: split int float bits 
     * </pre>
     *
     * <code>int32 some_floatp2 = 9;</code>
     * @return The someFloatp2.
     */
    int getSomeFloatp2();

    /**
     * <pre>
     * type before: sfixed64 | p2 
     * </pre>
     *
     * <code>sfixed64 some_sfixed64p2 = 15;</code>
     * @return The someSfixed64p2.
     */
    long getSomeSfixed64P2();

    /**
     * <pre>
     * type before: sfixed64 | p1 
     * </pre>
     *
     * <code>sfixed64 some_sfixed64p1 = 3;</code>
     * @return The someSfixed64p1.
     */
    long getSomeSfixed64P1();

    /**
     * <pre>
     * type before: float | representation: split int float bits 
     * </pre>
     *
     * <code>int32 some_floatp1 = 4;</code>
     * @return The someFloatp1.
     */
    int getSomeFloatp1();

    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>fixed64 some_fixed64 = 1;</code>
     * @return The someFixed64.
     */
    long getSomeFixed64();

    /**
     * <pre>
     * type before: bytes | representation: split bytes 
     * </pre>
     *
     * <code>bytes some_bytesp1 = 11;</code>
     * @return The someBytesp1.
     */
    com.google.protobuf.ByteString getSomeBytesp1();

    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>uint32 some_uint32 = 13;</code>
     * @return The someUint32.
     */
    int getSomeUint32();
  }
  /**
   * <pre>
   * Level 0, Encrypted using AES
   * </pre>
   *
   * Protobuf type {@code com.autogeneratedby.polymorph.allfieldsonce}
   */
  public  static final class allfieldsonce extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.autogeneratedby.polymorph.allfieldsonce)
      allfieldsonceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use allfieldsonce.newBuilder() to construct.
    private allfieldsonce(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private allfieldsonce() {
      someBoolean_ = "";
      someFixed32_ = "";
      someUint64_ = "";
      someString_ = com.google.protobuf.ByteString.EMPTY;
      someBytesp2_ = com.google.protobuf.ByteString.EMPTY;
      someBytesp1_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new allfieldsonce();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private allfieldsonce(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              someFixed64_ = input.readFixed64();
              break;
            }
            case 16: {

              someSint32_ = input.readSInt32();
              break;
            }
            case 25: {

              someSfixed64P1_ = input.readSFixed64();
              break;
            }
            case 32: {

              someFloatp1_ = input.readInt32();
              break;
            }
            case 42: {

              someBytesp2_ = input.readBytes();
              break;
            }
            case 53: {

              someSfixed32_ = input.readSFixed32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              someFixed32_ = s;
              break;
            }
            case 65: {

              someDouble_ = input.readDouble();
              break;
            }
            case 72: {

              someFloatp2_ = input.readInt32();
              break;
            }
            case 82: {

              someString_ = input.readBytes();
              break;
            }
            case 90: {

              someBytesp1_ = input.readBytes();
              break;
            }
            case 96: {

              someSint64_ = input.readSInt64();
              break;
            }
            case 104: {

              someUint32_ = input.readUInt32();
              break;
            }
            case 112: {

              someInt64_ = input.readInt64();
              break;
            }
            case 121: {

              someSfixed64P2_ = input.readSFixed64();
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              someBoolean_ = s;
              break;
            }
            case 136: {

              someInt32P1_ = input.readInt32();
              break;
            }
            case 144: {

              someInt32P2_ = input.readInt32();
              break;
            }
            case 154: {
              java.lang.String s = input.readStringRequireUtf8();

              someUint64_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autogeneratedby.polymorph.P1.internal_static_com_autogeneratedby_polymorph_allfieldsonce_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autogeneratedby.polymorph.P1.internal_static_com_autogeneratedby_polymorph_allfieldsonce_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autogeneratedby.polymorph.P1.allfieldsonce.class, com.autogeneratedby.polymorph.P1.allfieldsonce.Builder.class);
    }

    public static final int SOME_BOOLEAN_FIELD_NUMBER = 16;
    private volatile java.lang.Object someBoolean_;
    /**
     * <pre>
     * type before: bool 
     * </pre>
     *
     * <code>string some_boolean = 16;</code>
     * @return The someBoolean.
     */
    public java.lang.String getSomeBoolean() {
      java.lang.Object ref = someBoolean_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        someBoolean_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * type before: bool 
     * </pre>
     *
     * <code>string some_boolean = 16;</code>
     * @return The bytes for someBoolean.
     */
    public com.google.protobuf.ByteString
        getSomeBooleanBytes() {
      java.lang.Object ref = someBoolean_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        someBoolean_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOME_FIXED32_FIELD_NUMBER = 7;
    private volatile java.lang.Object someFixed32_;
    /**
     * <pre>
     * type before: fixed32 
     * </pre>
     *
     * <code>string some_fixed32 = 7;</code>
     * @return The someFixed32.
     */
    public java.lang.String getSomeFixed32() {
      java.lang.Object ref = someFixed32_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        someFixed32_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * type before: fixed32 
     * </pre>
     *
     * <code>string some_fixed32 = 7;</code>
     * @return The bytes for someFixed32.
     */
    public com.google.protobuf.ByteString
        getSomeFixed32Bytes() {
      java.lang.Object ref = someFixed32_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        someFixed32_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOME_UINT64_FIELD_NUMBER = 19;
    private volatile java.lang.Object someUint64_;
    /**
     * <pre>
     * type before: uint64 
     * </pre>
     *
     * <code>string some_uint64 = 19;</code>
     * @return The someUint64.
     */
    public java.lang.String getSomeUint64() {
      java.lang.Object ref = someUint64_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        someUint64_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * type before: uint64 
     * </pre>
     *
     * <code>string some_uint64 = 19;</code>
     * @return The bytes for someUint64.
     */
    public com.google.protobuf.ByteString
        getSomeUint64Bytes() {
      java.lang.Object ref = someUint64_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        someUint64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOME_SINT64_FIELD_NUMBER = 12;
    private long someSint64_;
    /**
     * <pre>
     * type before: sint64 | representation: negative number 
     * </pre>
     *
     * <code>sint64 some_sint64 = 12;</code>
     * @return The someSint64.
     */
    public long getSomeSint64() {
      return someSint64_;
    }

    public static final int SOME_INT64_FIELD_NUMBER = 14;
    private long someInt64_;
    /**
     * <pre>
     * type before: int64 | representation: negative number 
     * </pre>
     *
     * <code>int64 some_int64 = 14;</code>
     * @return The someInt64.
     */
    public long getSomeInt64() {
      return someInt64_;
    }

    public static final int SOME_DOUBLE_FIELD_NUMBER = 8;
    private double someDouble_;
    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>double some_double = 8;</code>
     * @return The someDouble.
     */
    public double getSomeDouble() {
      return someDouble_;
    }

    public static final int SOME_INT32P2_FIELD_NUMBER = 18;
    private int someInt32P2_;
    /**
     * <pre>
     * type before: int32 | p2 
     * </pre>
     *
     * <code>int32 some_int32p2 = 18;</code>
     * @return The someInt32p2.
     */
    public int getSomeInt32P2() {
      return someInt32P2_;
    }

    public static final int SOME_STRING_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString someString_;
    /**
     * <pre>
     * type before: string | representation: utf32 bytes 
     * </pre>
     *
     * <code>bytes some_string = 10;</code>
     * @return The someString.
     */
    public com.google.protobuf.ByteString getSomeString() {
      return someString_;
    }

    public static final int SOME_SFIXED32_FIELD_NUMBER = 6;
    private int someSfixed32_;
    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>sfixed32 some_sfixed32 = 6;</code>
     * @return The someSfixed32.
     */
    public int getSomeSfixed32() {
      return someSfixed32_;
    }

    public static final int SOME_INT32P1_FIELD_NUMBER = 17;
    private int someInt32P1_;
    /**
     * <pre>
     * type before: int32 | p1 
     * </pre>
     *
     * <code>int32 some_int32p1 = 17;</code>
     * @return The someInt32p1.
     */
    public int getSomeInt32P1() {
      return someInt32P1_;
    }

    public static final int SOME_SINT32_FIELD_NUMBER = 2;
    private int someSint32_;
    /**
     * <pre>
     * type before: sint32 | representation: negative number 
     * </pre>
     *
     * <code>sint32 some_sint32 = 2;</code>
     * @return The someSint32.
     */
    public int getSomeSint32() {
      return someSint32_;
    }

    public static final int SOME_BYTESP2_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString someBytesp2_;
    /**
     * <pre>
     * type before: bytes | representation: split bytes 
     * </pre>
     *
     * <code>bytes some_bytesp2 = 5;</code>
     * @return The someBytesp2.
     */
    public com.google.protobuf.ByteString getSomeBytesp2() {
      return someBytesp2_;
    }

    public static final int SOME_FLOATP2_FIELD_NUMBER = 9;
    private int someFloatp2_;
    /**
     * <pre>
     * type before: float | representation: split int float bits 
     * </pre>
     *
     * <code>int32 some_floatp2 = 9;</code>
     * @return The someFloatp2.
     */
    public int getSomeFloatp2() {
      return someFloatp2_;
    }

    public static final int SOME_SFIXED64P2_FIELD_NUMBER = 15;
    private long someSfixed64P2_;
    /**
     * <pre>
     * type before: sfixed64 | p2 
     * </pre>
     *
     * <code>sfixed64 some_sfixed64p2 = 15;</code>
     * @return The someSfixed64p2.
     */
    public long getSomeSfixed64P2() {
      return someSfixed64P2_;
    }

    public static final int SOME_SFIXED64P1_FIELD_NUMBER = 3;
    private long someSfixed64P1_;
    /**
     * <pre>
     * type before: sfixed64 | p1 
     * </pre>
     *
     * <code>sfixed64 some_sfixed64p1 = 3;</code>
     * @return The someSfixed64p1.
     */
    public long getSomeSfixed64P1() {
      return someSfixed64P1_;
    }

    public static final int SOME_FLOATP1_FIELD_NUMBER = 4;
    private int someFloatp1_;
    /**
     * <pre>
     * type before: float | representation: split int float bits 
     * </pre>
     *
     * <code>int32 some_floatp1 = 4;</code>
     * @return The someFloatp1.
     */
    public int getSomeFloatp1() {
      return someFloatp1_;
    }

    public static final int SOME_FIXED64_FIELD_NUMBER = 1;
    private long someFixed64_;
    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>fixed64 some_fixed64 = 1;</code>
     * @return The someFixed64.
     */
    public long getSomeFixed64() {
      return someFixed64_;
    }

    public static final int SOME_BYTESP1_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString someBytesp1_;
    /**
     * <pre>
     * type before: bytes | representation: split bytes 
     * </pre>
     *
     * <code>bytes some_bytesp1 = 11;</code>
     * @return The someBytesp1.
     */
    public com.google.protobuf.ByteString getSomeBytesp1() {
      return someBytesp1_;
    }

    public static final int SOME_UINT32_FIELD_NUMBER = 13;
    private int someUint32_;
    /**
     * <pre>
     * type unmodified 
     * </pre>
     *
     * <code>uint32 some_uint32 = 13;</code>
     * @return The someUint32.
     */
    public int getSomeUint32() {
      return someUint32_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (someFixed64_ != 0L) {
        output.writeFixed64(1, someFixed64_);
      }
      if (someSint32_ != 0) {
        output.writeSInt32(2, someSint32_);
      }
      if (someSfixed64P1_ != 0L) {
        output.writeSFixed64(3, someSfixed64P1_);
      }
      if (someFloatp1_ != 0) {
        output.writeInt32(4, someFloatp1_);
      }
      if (!someBytesp2_.isEmpty()) {
        output.writeBytes(5, someBytesp2_);
      }
      if (someSfixed32_ != 0) {
        output.writeSFixed32(6, someSfixed32_);
      }
      if (!getSomeFixed32Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, someFixed32_);
      }
      if (someDouble_ != 0D) {
        output.writeDouble(8, someDouble_);
      }
      if (someFloatp2_ != 0) {
        output.writeInt32(9, someFloatp2_);
      }
      if (!someString_.isEmpty()) {
        output.writeBytes(10, someString_);
      }
      if (!someBytesp1_.isEmpty()) {
        output.writeBytes(11, someBytesp1_);
      }
      if (someSint64_ != 0L) {
        output.writeSInt64(12, someSint64_);
      }
      if (someUint32_ != 0) {
        output.writeUInt32(13, someUint32_);
      }
      if (someInt64_ != 0L) {
        output.writeInt64(14, someInt64_);
      }
      if (someSfixed64P2_ != 0L) {
        output.writeSFixed64(15, someSfixed64P2_);
      }
      if (!getSomeBooleanBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, someBoolean_);
      }
      if (someInt32P1_ != 0) {
        output.writeInt32(17, someInt32P1_);
      }
      if (someInt32P2_ != 0) {
        output.writeInt32(18, someInt32P2_);
      }
      if (!getSomeUint64Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, someUint64_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (someFixed64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, someFixed64_);
      }
      if (someSint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, someSint32_);
      }
      if (someSfixed64P1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(3, someSfixed64P1_);
      }
      if (someFloatp1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, someFloatp1_);
      }
      if (!someBytesp2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, someBytesp2_);
      }
      if (someSfixed32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(6, someSfixed32_);
      }
      if (!getSomeFixed32Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, someFixed32_);
      }
      if (someDouble_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, someDouble_);
      }
      if (someFloatp2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, someFloatp2_);
      }
      if (!someString_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, someString_);
      }
      if (!someBytesp1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, someBytesp1_);
      }
      if (someSint64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(12, someSint64_);
      }
      if (someUint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, someUint32_);
      }
      if (someInt64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, someInt64_);
      }
      if (someSfixed64P2_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(15, someSfixed64P2_);
      }
      if (!getSomeBooleanBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, someBoolean_);
      }
      if (someInt32P1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, someInt32P1_);
      }
      if (someInt32P2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, someInt32P2_);
      }
      if (!getSomeUint64Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, someUint64_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.autogeneratedby.polymorph.P1.allfieldsonce)) {
        return super.equals(obj);
      }
      com.autogeneratedby.polymorph.P1.allfieldsonce other = (com.autogeneratedby.polymorph.P1.allfieldsonce) obj;

      if (!getSomeBoolean()
          .equals(other.getSomeBoolean())) return false;
      if (!getSomeFixed32()
          .equals(other.getSomeFixed32())) return false;
      if (!getSomeUint64()
          .equals(other.getSomeUint64())) return false;
      if (getSomeSint64()
          != other.getSomeSint64()) return false;
      if (getSomeInt64()
          != other.getSomeInt64()) return false;
      if (java.lang.Double.doubleToLongBits(getSomeDouble())
          != java.lang.Double.doubleToLongBits(
              other.getSomeDouble())) return false;
      if (getSomeInt32P2()
          != other.getSomeInt32P2()) return false;
      if (!getSomeString()
          .equals(other.getSomeString())) return false;
      if (getSomeSfixed32()
          != other.getSomeSfixed32()) return false;
      if (getSomeInt32P1()
          != other.getSomeInt32P1()) return false;
      if (getSomeSint32()
          != other.getSomeSint32()) return false;
      if (!getSomeBytesp2()
          .equals(other.getSomeBytesp2())) return false;
      if (getSomeFloatp2()
          != other.getSomeFloatp2()) return false;
      if (getSomeSfixed64P2()
          != other.getSomeSfixed64P2()) return false;
      if (getSomeSfixed64P1()
          != other.getSomeSfixed64P1()) return false;
      if (getSomeFloatp1()
          != other.getSomeFloatp1()) return false;
      if (getSomeFixed64()
          != other.getSomeFixed64()) return false;
      if (!getSomeBytesp1()
          .equals(other.getSomeBytesp1())) return false;
      if (getSomeUint32()
          != other.getSomeUint32()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOME_BOOLEAN_FIELD_NUMBER;
      hash = (53 * hash) + getSomeBoolean().hashCode();
      hash = (37 * hash) + SOME_FIXED32_FIELD_NUMBER;
      hash = (53 * hash) + getSomeFixed32().hashCode();
      hash = (37 * hash) + SOME_UINT64_FIELD_NUMBER;
      hash = (53 * hash) + getSomeUint64().hashCode();
      hash = (37 * hash) + SOME_SINT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSomeSint64());
      hash = (37 * hash) + SOME_INT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSomeInt64());
      hash = (37 * hash) + SOME_DOUBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSomeDouble()));
      hash = (37 * hash) + SOME_INT32P2_FIELD_NUMBER;
      hash = (53 * hash) + getSomeInt32P2();
      hash = (37 * hash) + SOME_STRING_FIELD_NUMBER;
      hash = (53 * hash) + getSomeString().hashCode();
      hash = (37 * hash) + SOME_SFIXED32_FIELD_NUMBER;
      hash = (53 * hash) + getSomeSfixed32();
      hash = (37 * hash) + SOME_INT32P1_FIELD_NUMBER;
      hash = (53 * hash) + getSomeInt32P1();
      hash = (37 * hash) + SOME_SINT32_FIELD_NUMBER;
      hash = (53 * hash) + getSomeSint32();
      hash = (37 * hash) + SOME_BYTESP2_FIELD_NUMBER;
      hash = (53 * hash) + getSomeBytesp2().hashCode();
      hash = (37 * hash) + SOME_FLOATP2_FIELD_NUMBER;
      hash = (53 * hash) + getSomeFloatp2();
      hash = (37 * hash) + SOME_SFIXED64P2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSomeSfixed64P2());
      hash = (37 * hash) + SOME_SFIXED64P1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSomeSfixed64P1());
      hash = (37 * hash) + SOME_FLOATP1_FIELD_NUMBER;
      hash = (53 * hash) + getSomeFloatp1();
      hash = (37 * hash) + SOME_FIXED64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSomeFixed64());
      hash = (37 * hash) + SOME_BYTESP1_FIELD_NUMBER;
      hash = (53 * hash) + getSomeBytesp1().hashCode();
      hash = (37 * hash) + SOME_UINT32_FIELD_NUMBER;
      hash = (53 * hash) + getSomeUint32();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.autogeneratedby.polymorph.P1.allfieldsonce parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.autogeneratedby.polymorph.P1.allfieldsonce prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Level 0, Encrypted using AES
     * </pre>
     *
     * Protobuf type {@code com.autogeneratedby.polymorph.allfieldsonce}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autogeneratedby.polymorph.allfieldsonce)
        com.autogeneratedby.polymorph.P1.allfieldsonceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autogeneratedby.polymorph.P1.internal_static_com_autogeneratedby_polymorph_allfieldsonce_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autogeneratedby.polymorph.P1.internal_static_com_autogeneratedby_polymorph_allfieldsonce_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autogeneratedby.polymorph.P1.allfieldsonce.class, com.autogeneratedby.polymorph.P1.allfieldsonce.Builder.class);
      }

      // Construct using com.autogeneratedby.polymorph.P1.allfieldsonce.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        someBoolean_ = "";

        someFixed32_ = "";

        someUint64_ = "";

        someSint64_ = 0L;

        someInt64_ = 0L;

        someDouble_ = 0D;

        someInt32P2_ = 0;

        someString_ = com.google.protobuf.ByteString.EMPTY;

        someSfixed32_ = 0;

        someInt32P1_ = 0;

        someSint32_ = 0;

        someBytesp2_ = com.google.protobuf.ByteString.EMPTY;

        someFloatp2_ = 0;

        someSfixed64P2_ = 0L;

        someSfixed64P1_ = 0L;

        someFloatp1_ = 0;

        someFixed64_ = 0L;

        someBytesp1_ = com.google.protobuf.ByteString.EMPTY;

        someUint32_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autogeneratedby.polymorph.P1.internal_static_com_autogeneratedby_polymorph_allfieldsonce_descriptor;
      }

      @java.lang.Override
      public com.autogeneratedby.polymorph.P1.allfieldsonce getDefaultInstanceForType() {
        return com.autogeneratedby.polymorph.P1.allfieldsonce.getDefaultInstance();
      }

      @java.lang.Override
      public com.autogeneratedby.polymorph.P1.allfieldsonce build() {
        com.autogeneratedby.polymorph.P1.allfieldsonce result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.autogeneratedby.polymorph.P1.allfieldsonce buildPartial() {
        com.autogeneratedby.polymorph.P1.allfieldsonce result = new com.autogeneratedby.polymorph.P1.allfieldsonce(this);
        result.someBoolean_ = someBoolean_;
        result.someFixed32_ = someFixed32_;
        result.someUint64_ = someUint64_;
        result.someSint64_ = someSint64_;
        result.someInt64_ = someInt64_;
        result.someDouble_ = someDouble_;
        result.someInt32P2_ = someInt32P2_;
        result.someString_ = someString_;
        result.someSfixed32_ = someSfixed32_;
        result.someInt32P1_ = someInt32P1_;
        result.someSint32_ = someSint32_;
        result.someBytesp2_ = someBytesp2_;
        result.someFloatp2_ = someFloatp2_;
        result.someSfixed64P2_ = someSfixed64P2_;
        result.someSfixed64P1_ = someSfixed64P1_;
        result.someFloatp1_ = someFloatp1_;
        result.someFixed64_ = someFixed64_;
        result.someBytesp1_ = someBytesp1_;
        result.someUint32_ = someUint32_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autogeneratedby.polymorph.P1.allfieldsonce) {
          return mergeFrom((com.autogeneratedby.polymorph.P1.allfieldsonce)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autogeneratedby.polymorph.P1.allfieldsonce other) {
        if (other == com.autogeneratedby.polymorph.P1.allfieldsonce.getDefaultInstance()) return this;
        if (!other.getSomeBoolean().isEmpty()) {
          someBoolean_ = other.someBoolean_;
          onChanged();
        }
        if (!other.getSomeFixed32().isEmpty()) {
          someFixed32_ = other.someFixed32_;
          onChanged();
        }
        if (!other.getSomeUint64().isEmpty()) {
          someUint64_ = other.someUint64_;
          onChanged();
        }
        if (other.getSomeSint64() != 0L) {
          setSomeSint64(other.getSomeSint64());
        }
        if (other.getSomeInt64() != 0L) {
          setSomeInt64(other.getSomeInt64());
        }
        if (other.getSomeDouble() != 0D) {
          setSomeDouble(other.getSomeDouble());
        }
        if (other.getSomeInt32P2() != 0) {
          setSomeInt32P2(other.getSomeInt32P2());
        }
        if (other.getSomeString() != com.google.protobuf.ByteString.EMPTY) {
          setSomeString(other.getSomeString());
        }
        if (other.getSomeSfixed32() != 0) {
          setSomeSfixed32(other.getSomeSfixed32());
        }
        if (other.getSomeInt32P1() != 0) {
          setSomeInt32P1(other.getSomeInt32P1());
        }
        if (other.getSomeSint32() != 0) {
          setSomeSint32(other.getSomeSint32());
        }
        if (other.getSomeBytesp2() != com.google.protobuf.ByteString.EMPTY) {
          setSomeBytesp2(other.getSomeBytesp2());
        }
        if (other.getSomeFloatp2() != 0) {
          setSomeFloatp2(other.getSomeFloatp2());
        }
        if (other.getSomeSfixed64P2() != 0L) {
          setSomeSfixed64P2(other.getSomeSfixed64P2());
        }
        if (other.getSomeSfixed64P1() != 0L) {
          setSomeSfixed64P1(other.getSomeSfixed64P1());
        }
        if (other.getSomeFloatp1() != 0) {
          setSomeFloatp1(other.getSomeFloatp1());
        }
        if (other.getSomeFixed64() != 0L) {
          setSomeFixed64(other.getSomeFixed64());
        }
        if (other.getSomeBytesp1() != com.google.protobuf.ByteString.EMPTY) {
          setSomeBytesp1(other.getSomeBytesp1());
        }
        if (other.getSomeUint32() != 0) {
          setSomeUint32(other.getSomeUint32());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autogeneratedby.polymorph.P1.allfieldsonce parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autogeneratedby.polymorph.P1.allfieldsonce) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object someBoolean_ = "";
      /**
       * <pre>
       * type before: bool 
       * </pre>
       *
       * <code>string some_boolean = 16;</code>
       * @return The someBoolean.
       */
      public java.lang.String getSomeBoolean() {
        java.lang.Object ref = someBoolean_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          someBoolean_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * type before: bool 
       * </pre>
       *
       * <code>string some_boolean = 16;</code>
       * @return The bytes for someBoolean.
       */
      public com.google.protobuf.ByteString
          getSomeBooleanBytes() {
        java.lang.Object ref = someBoolean_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          someBoolean_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * type before: bool 
       * </pre>
       *
       * <code>string some_boolean = 16;</code>
       * @param value The someBoolean to set.
       * @return This builder for chaining.
       */
      public Builder setSomeBoolean(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someBoolean_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: bool 
       * </pre>
       *
       * <code>string some_boolean = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeBoolean() {
        
        someBoolean_ = getDefaultInstance().getSomeBoolean();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: bool 
       * </pre>
       *
       * <code>string some_boolean = 16;</code>
       * @param value The bytes for someBoolean to set.
       * @return This builder for chaining.
       */
      public Builder setSomeBooleanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        someBoolean_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object someFixed32_ = "";
      /**
       * <pre>
       * type before: fixed32 
       * </pre>
       *
       * <code>string some_fixed32 = 7;</code>
       * @return The someFixed32.
       */
      public java.lang.String getSomeFixed32() {
        java.lang.Object ref = someFixed32_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          someFixed32_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * type before: fixed32 
       * </pre>
       *
       * <code>string some_fixed32 = 7;</code>
       * @return The bytes for someFixed32.
       */
      public com.google.protobuf.ByteString
          getSomeFixed32Bytes() {
        java.lang.Object ref = someFixed32_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          someFixed32_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * type before: fixed32 
       * </pre>
       *
       * <code>string some_fixed32 = 7;</code>
       * @param value The someFixed32 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeFixed32(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someFixed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: fixed32 
       * </pre>
       *
       * <code>string some_fixed32 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeFixed32() {
        
        someFixed32_ = getDefaultInstance().getSomeFixed32();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: fixed32 
       * </pre>
       *
       * <code>string some_fixed32 = 7;</code>
       * @param value The bytes for someFixed32 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeFixed32Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        someFixed32_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object someUint64_ = "";
      /**
       * <pre>
       * type before: uint64 
       * </pre>
       *
       * <code>string some_uint64 = 19;</code>
       * @return The someUint64.
       */
      public java.lang.String getSomeUint64() {
        java.lang.Object ref = someUint64_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          someUint64_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * type before: uint64 
       * </pre>
       *
       * <code>string some_uint64 = 19;</code>
       * @return The bytes for someUint64.
       */
      public com.google.protobuf.ByteString
          getSomeUint64Bytes() {
        java.lang.Object ref = someUint64_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          someUint64_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * type before: uint64 
       * </pre>
       *
       * <code>string some_uint64 = 19;</code>
       * @param value The someUint64 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeUint64(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someUint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: uint64 
       * </pre>
       *
       * <code>string some_uint64 = 19;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeUint64() {
        
        someUint64_ = getDefaultInstance().getSomeUint64();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: uint64 
       * </pre>
       *
       * <code>string some_uint64 = 19;</code>
       * @param value The bytes for someUint64 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeUint64Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        someUint64_ = value;
        onChanged();
        return this;
      }

      private long someSint64_ ;
      /**
       * <pre>
       * type before: sint64 | representation: negative number 
       * </pre>
       *
       * <code>sint64 some_sint64 = 12;</code>
       * @return The someSint64.
       */
      public long getSomeSint64() {
        return someSint64_;
      }
      /**
       * <pre>
       * type before: sint64 | representation: negative number 
       * </pre>
       *
       * <code>sint64 some_sint64 = 12;</code>
       * @param value The someSint64 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeSint64(long value) {
        
        someSint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: sint64 | representation: negative number 
       * </pre>
       *
       * <code>sint64 some_sint64 = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeSint64() {
        
        someSint64_ = 0L;
        onChanged();
        return this;
      }

      private long someInt64_ ;
      /**
       * <pre>
       * type before: int64 | representation: negative number 
       * </pre>
       *
       * <code>int64 some_int64 = 14;</code>
       * @return The someInt64.
       */
      public long getSomeInt64() {
        return someInt64_;
      }
      /**
       * <pre>
       * type before: int64 | representation: negative number 
       * </pre>
       *
       * <code>int64 some_int64 = 14;</code>
       * @param value The someInt64 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeInt64(long value) {
        
        someInt64_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: int64 | representation: negative number 
       * </pre>
       *
       * <code>int64 some_int64 = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeInt64() {
        
        someInt64_ = 0L;
        onChanged();
        return this;
      }

      private double someDouble_ ;
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>double some_double = 8;</code>
       * @return The someDouble.
       */
      public double getSomeDouble() {
        return someDouble_;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>double some_double = 8;</code>
       * @param value The someDouble to set.
       * @return This builder for chaining.
       */
      public Builder setSomeDouble(double value) {
        
        someDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>double some_double = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeDouble() {
        
        someDouble_ = 0D;
        onChanged();
        return this;
      }

      private int someInt32P2_ ;
      /**
       * <pre>
       * type before: int32 | p2 
       * </pre>
       *
       * <code>int32 some_int32p2 = 18;</code>
       * @return The someInt32p2.
       */
      public int getSomeInt32P2() {
        return someInt32P2_;
      }
      /**
       * <pre>
       * type before: int32 | p2 
       * </pre>
       *
       * <code>int32 some_int32p2 = 18;</code>
       * @param value The someInt32p2 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeInt32P2(int value) {
        
        someInt32P2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: int32 | p2 
       * </pre>
       *
       * <code>int32 some_int32p2 = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeInt32P2() {
        
        someInt32P2_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString someString_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * type before: string | representation: utf32 bytes 
       * </pre>
       *
       * <code>bytes some_string = 10;</code>
       * @return The someString.
       */
      public com.google.protobuf.ByteString getSomeString() {
        return someString_;
      }
      /**
       * <pre>
       * type before: string | representation: utf32 bytes 
       * </pre>
       *
       * <code>bytes some_string = 10;</code>
       * @param value The someString to set.
       * @return This builder for chaining.
       */
      public Builder setSomeString(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someString_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: string | representation: utf32 bytes 
       * </pre>
       *
       * <code>bytes some_string = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeString() {
        
        someString_ = getDefaultInstance().getSomeString();
        onChanged();
        return this;
      }

      private int someSfixed32_ ;
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>sfixed32 some_sfixed32 = 6;</code>
       * @return The someSfixed32.
       */
      public int getSomeSfixed32() {
        return someSfixed32_;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>sfixed32 some_sfixed32 = 6;</code>
       * @param value The someSfixed32 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeSfixed32(int value) {
        
        someSfixed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>sfixed32 some_sfixed32 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeSfixed32() {
        
        someSfixed32_ = 0;
        onChanged();
        return this;
      }

      private int someInt32P1_ ;
      /**
       * <pre>
       * type before: int32 | p1 
       * </pre>
       *
       * <code>int32 some_int32p1 = 17;</code>
       * @return The someInt32p1.
       */
      public int getSomeInt32P1() {
        return someInt32P1_;
      }
      /**
       * <pre>
       * type before: int32 | p1 
       * </pre>
       *
       * <code>int32 some_int32p1 = 17;</code>
       * @param value The someInt32p1 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeInt32P1(int value) {
        
        someInt32P1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: int32 | p1 
       * </pre>
       *
       * <code>int32 some_int32p1 = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeInt32P1() {
        
        someInt32P1_ = 0;
        onChanged();
        return this;
      }

      private int someSint32_ ;
      /**
       * <pre>
       * type before: sint32 | representation: negative number 
       * </pre>
       *
       * <code>sint32 some_sint32 = 2;</code>
       * @return The someSint32.
       */
      public int getSomeSint32() {
        return someSint32_;
      }
      /**
       * <pre>
       * type before: sint32 | representation: negative number 
       * </pre>
       *
       * <code>sint32 some_sint32 = 2;</code>
       * @param value The someSint32 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeSint32(int value) {
        
        someSint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: sint32 | representation: negative number 
       * </pre>
       *
       * <code>sint32 some_sint32 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeSint32() {
        
        someSint32_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString someBytesp2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * type before: bytes | representation: split bytes 
       * </pre>
       *
       * <code>bytes some_bytesp2 = 5;</code>
       * @return The someBytesp2.
       */
      public com.google.protobuf.ByteString getSomeBytesp2() {
        return someBytesp2_;
      }
      /**
       * <pre>
       * type before: bytes | representation: split bytes 
       * </pre>
       *
       * <code>bytes some_bytesp2 = 5;</code>
       * @param value The someBytesp2 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeBytesp2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someBytesp2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: bytes | representation: split bytes 
       * </pre>
       *
       * <code>bytes some_bytesp2 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeBytesp2() {
        
        someBytesp2_ = getDefaultInstance().getSomeBytesp2();
        onChanged();
        return this;
      }

      private int someFloatp2_ ;
      /**
       * <pre>
       * type before: float | representation: split int float bits 
       * </pre>
       *
       * <code>int32 some_floatp2 = 9;</code>
       * @return The someFloatp2.
       */
      public int getSomeFloatp2() {
        return someFloatp2_;
      }
      /**
       * <pre>
       * type before: float | representation: split int float bits 
       * </pre>
       *
       * <code>int32 some_floatp2 = 9;</code>
       * @param value The someFloatp2 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeFloatp2(int value) {
        
        someFloatp2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: float | representation: split int float bits 
       * </pre>
       *
       * <code>int32 some_floatp2 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeFloatp2() {
        
        someFloatp2_ = 0;
        onChanged();
        return this;
      }

      private long someSfixed64P2_ ;
      /**
       * <pre>
       * type before: sfixed64 | p2 
       * </pre>
       *
       * <code>sfixed64 some_sfixed64p2 = 15;</code>
       * @return The someSfixed64p2.
       */
      public long getSomeSfixed64P2() {
        return someSfixed64P2_;
      }
      /**
       * <pre>
       * type before: sfixed64 | p2 
       * </pre>
       *
       * <code>sfixed64 some_sfixed64p2 = 15;</code>
       * @param value The someSfixed64p2 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeSfixed64P2(long value) {
        
        someSfixed64P2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: sfixed64 | p2 
       * </pre>
       *
       * <code>sfixed64 some_sfixed64p2 = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeSfixed64P2() {
        
        someSfixed64P2_ = 0L;
        onChanged();
        return this;
      }

      private long someSfixed64P1_ ;
      /**
       * <pre>
       * type before: sfixed64 | p1 
       * </pre>
       *
       * <code>sfixed64 some_sfixed64p1 = 3;</code>
       * @return The someSfixed64p1.
       */
      public long getSomeSfixed64P1() {
        return someSfixed64P1_;
      }
      /**
       * <pre>
       * type before: sfixed64 | p1 
       * </pre>
       *
       * <code>sfixed64 some_sfixed64p1 = 3;</code>
       * @param value The someSfixed64p1 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeSfixed64P1(long value) {
        
        someSfixed64P1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: sfixed64 | p1 
       * </pre>
       *
       * <code>sfixed64 some_sfixed64p1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeSfixed64P1() {
        
        someSfixed64P1_ = 0L;
        onChanged();
        return this;
      }

      private int someFloatp1_ ;
      /**
       * <pre>
       * type before: float | representation: split int float bits 
       * </pre>
       *
       * <code>int32 some_floatp1 = 4;</code>
       * @return The someFloatp1.
       */
      public int getSomeFloatp1() {
        return someFloatp1_;
      }
      /**
       * <pre>
       * type before: float | representation: split int float bits 
       * </pre>
       *
       * <code>int32 some_floatp1 = 4;</code>
       * @param value The someFloatp1 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeFloatp1(int value) {
        
        someFloatp1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: float | representation: split int float bits 
       * </pre>
       *
       * <code>int32 some_floatp1 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeFloatp1() {
        
        someFloatp1_ = 0;
        onChanged();
        return this;
      }

      private long someFixed64_ ;
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>fixed64 some_fixed64 = 1;</code>
       * @return The someFixed64.
       */
      public long getSomeFixed64() {
        return someFixed64_;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>fixed64 some_fixed64 = 1;</code>
       * @param value The someFixed64 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeFixed64(long value) {
        
        someFixed64_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>fixed64 some_fixed64 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeFixed64() {
        
        someFixed64_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString someBytesp1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * type before: bytes | representation: split bytes 
       * </pre>
       *
       * <code>bytes some_bytesp1 = 11;</code>
       * @return The someBytesp1.
       */
      public com.google.protobuf.ByteString getSomeBytesp1() {
        return someBytesp1_;
      }
      /**
       * <pre>
       * type before: bytes | representation: split bytes 
       * </pre>
       *
       * <code>bytes some_bytesp1 = 11;</code>
       * @param value The someBytesp1 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeBytesp1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someBytesp1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type before: bytes | representation: split bytes 
       * </pre>
       *
       * <code>bytes some_bytesp1 = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeBytesp1() {
        
        someBytesp1_ = getDefaultInstance().getSomeBytesp1();
        onChanged();
        return this;
      }

      private int someUint32_ ;
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>uint32 some_uint32 = 13;</code>
       * @return The someUint32.
       */
      public int getSomeUint32() {
        return someUint32_;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>uint32 some_uint32 = 13;</code>
       * @param value The someUint32 to set.
       * @return This builder for chaining.
       */
      public Builder setSomeUint32(int value) {
        
        someUint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * type unmodified 
       * </pre>
       *
       * <code>uint32 some_uint32 = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearSomeUint32() {
        
        someUint32_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.autogeneratedby.polymorph.allfieldsonce)
    }

    // @@protoc_insertion_point(class_scope:com.autogeneratedby.polymorph.allfieldsonce)
    private static final com.autogeneratedby.polymorph.P1.allfieldsonce DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.autogeneratedby.polymorph.P1.allfieldsonce();
    }

    public static com.autogeneratedby.polymorph.P1.allfieldsonce getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<allfieldsonce>
        PARSER = new com.google.protobuf.AbstractParser<allfieldsonce>() {
      @java.lang.Override
      public allfieldsonce parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new allfieldsonce(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<allfieldsonce> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<allfieldsonce> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.autogeneratedby.polymorph.P1.allfieldsonce getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autogeneratedby_polymorph_allfieldsonce_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_autogeneratedby_polymorph_allfieldsonce_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010p1.proto\022\035com.autogeneratedby.polymorp" +
      "h\"\260\003\n\rallfieldsonce\022\024\n\014some_boolean\030\020 \001(" +
      "\t\022\024\n\014some_fixed32\030\007 \001(\t\022\023\n\013some_uint64\030\023" +
      " \001(\t\022\023\n\013some_sint64\030\014 \001(\022\022\022\n\nsome_int64\030" +
      "\016 \001(\003\022\023\n\013some_double\030\010 \001(\001\022\024\n\014some_int32" +
      "p2\030\022 \001(\005\022\023\n\013some_string\030\n \001(\014\022\025\n\rsome_sf" +
      "ixed32\030\006 \001(\017\022\024\n\014some_int32p1\030\021 \001(\005\022\023\n\013so" +
      "me_sint32\030\002 \001(\021\022\024\n\014some_bytesp2\030\005 \001(\014\022\024\n" +
      "\014some_floatp2\030\t \001(\005\022\027\n\017some_sfixed64p2\030\017" +
      " \001(\020\022\027\n\017some_sfixed64p1\030\003 \001(\020\022\024\n\014some_fl" +
      "oatp1\030\004 \001(\005\022\024\n\014some_fixed64\030\001 \001(\006\022\024\n\014som" +
      "e_bytesp1\030\013 \001(\014\022\023\n\013some_uint32\030\r \001(\rb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_autogeneratedby_polymorph_allfieldsonce_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autogeneratedby_polymorph_allfieldsonce_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_autogeneratedby_polymorph_allfieldsonce_descriptor,
        new java.lang.String[] { "SomeBoolean", "SomeFixed32", "SomeUint64", "SomeSint64", "SomeInt64", "SomeDouble", "SomeInt32P2", "SomeString", "SomeSfixed32", "SomeInt32P1", "SomeSint32", "SomeBytesp2", "SomeFloatp2", "SomeSfixed64P2", "SomeSfixed64P1", "SomeFloatp1", "SomeFixed64", "SomeBytesp1", "SomeUint32", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
