package com.uhh.code.polymorph.protobuilder;

import java.util.LinkedList;
import java.util.List;

// Builder for Protos (.proto files)
public class ProtoBuilder
{
    // Name of the Proto
    private String name;
    // Package Name of the Proto
    private String packageName;
    // Top-Level Messages (message definitions within the Proto)
    private List<ProtoMessage> protoMessages;

    public ProtoBuilder(String name)
    {
        // Initialize the fields
        this.protoMessages = new LinkedList<>();
        this.name = name;
    }

    public ProtoMessage createProto(String fieldName)
    {
        // Create a new Message
        var protoMessage = new ProtoMessage(fieldName);
        // Add it to the existing Messages
        protoMessages.add(protoMessage);

        return protoMessage;
    }

    public void setPackageName(String packageName)
    {
        this.packageName = packageName;
    }

    public String build()
    {
        // Proto always starts with syntax "proto3"
        String fullProto = "syntax = \"proto3\";\n\n";

        // If there is a package name, append it
        if (packageName != null)
        {
            fullProto = fullProto + "package " + packageName + ";\n";
        }

        for(var message : protoMessages)
        {
            // Call the builder for the Message
            var builtMessage = message.build();

            // Print the fully built Message out
            System.out.println("ProtoBuilder.build:");
            System.out.println(builtMessage);

            // Append to full Proto
            fullProto = fullProto + builtMessage + "\n\n";
        }

        // Prefix it to let developers know it was autogenerated by Polymorph
        return "/* Autogenerated .proto file by Polymorph\nName: " + name + "\n\n*/\n" + fullProto;
    }
}
